.TH "TRAIN" 3 "Za 6 Jun 2020" "Version 0.1" "FragScanTibo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TRAIN
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hmm\&.h>\fP
.SS "Public Attributen"

.in +1c
.ti -1c
.RI "double \fBtrans\fP [44][6][16][4]"
.br
.ti -1c
.RI "double \fBrtrans\fP [44][6][16][4]"
.br
.ti -1c
.RI "double \fBnoncoding\fP [44][4][4]"
.br
.ti -1c
.RI "double \fBstart\fP [44][61][64]"
.br
.ti -1c
.RI "double \fBstop\fP [44][61][64]"
.br
.ti -1c
.RI "double \fBstart1\fP [44][61][64]"
.br
.ti -1c
.RI "double \fBstop1\fP [44][61][64]"
.br
.ti -1c
.RI "double \fBS_dist\fP [44][6]"
.br
.ti -1c
.RI "double \fBE_dist\fP [44][6]"
.br
.ti -1c
.RI "double \fBS1_dist\fP [44][6]"
.br
.ti -1c
.RI "double \fBE1_dist\fP [44][6]"
.br
.in -1c
.SH "Documentatie van data members"
.PP 
.SS "double E1_dist[44][6]"

.SS "double E_dist[44][6]"

.SS "double noncoding[44][4][4]"

.SS "double rtrans[44][6][16][4]"

.SS "double S1_dist[44][6]"

.SS "double S_dist[44][6]"

.SS "double start[44][61][64]"

.SS "double start1[44][61][64]"

.SS "double stop[44][61][64]"

.SS "double stop1[44][61][64]"

.SS "double trans[44][6][16][4]"


.SH "Auteur"
.PP 
Automatisch gegenereerd door Doxygen voor FragScanTibo uit de programmatekst\&.
