.TH "FragGeneScan1.31/run_hmm.c" 3 "Vr 5 Jun 2020" "Version 0.1" "FragScanTibo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FragGeneScan1.31/run_hmm.c
.SH SYNOPSIS
.br
.PP
\fC#include <ctype\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'hmm\&.h'\fP
.br
\fC#include <pthread\&.h>\fP
.br

.SS "Klassen"

.in +1c
.ti -1c
.RI "struct \fBthread_data\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADD_LEN\fP   1024"
.br
.ti -1c
.RI "#define \fBSTRINGLEN\fP   4096"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBthread_data\fP \fBthread_data\fP"
.br
.in -1c
.SS "Functies"

.in +1c
.ti -1c
.RI "void * \fBthread_func\fP (void *threadarr)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.ti -1c
.RI "int \fBappendSeq\fP (char *input, char **seq, int input_max)"
.br
.in -1c
.SH "Documentatie van macro's"
.PP 
.SS "#define ADD_LEN   1024"

.SS "#define STRINGLEN   4096"

.SH "Documentatie van typedefs"
.PP 
.SS "typedef struct \fBthread_data\fP \fBthread_data\fP"

.SH "Documentatie van functies"
.PP 
.SS "int appendSeq (char * input, char ** seq, int input_max)"

.SS "int main (int argc, char ** argv)"

.SS "void * thread_func (void * threadarr)"

.SH "Auteur"
.PP 
Automatisch gegenereerd door Doxygen voor FragScanTibo uit de programmatekst\&.
