.TH "thread_data" 3 "Vr 5 Jun 2020" "Version 0.1" "FragScanTibo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thread_data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributen"

.in +1c
.ti -1c
.RI "FILE * \fBout\fP"
.br
.ti -1c
.RI "FILE * \fBaa\fP"
.br
.ti -1c
.RI "FILE * \fBdna\fP"
.br
.ti -1c
.RI "char * \fBobs_head\fP"
.br
.ti -1c
.RI "char * \fBobs_seq\fP"
.br
.ti -1c
.RI "int \fBwholegenome\fP"
.br
.ti -1c
.RI "int \fBcg\fP"
.br
.ti -1c
.RI "int \fBformat\fP"
.br
.ti -1c
.RI "\fBHMM\fP * \fBhmm\fP"
.br
.ti -1c
.RI "\fBTRAIN\fP * \fBtrain\fP"
.br
.in -1c
.SH "Documentatie van data members"
.PP 
.SS "FILE* aa"

.SS "int cg"

.SS "FILE* dna"

.SS "int format"

.SS "\fBHMM\fP* hmm"

.SS "char* obs_head"

.SS "char* obs_seq"

.SS "FILE* out"

.SS "\fBTRAIN\fP* train"

.SS "int wholegenome"


.SH "Auteur"
.PP 
Automatisch gegenereerd door Doxygen voor FragScanTibo uit de programmatekst\&.
