.TH "src Folder Referentie" 3 "Zo 7 Jun 2020" "Version 0.1" "FragScanTibo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Folder Referentie
.SH SYNOPSIS
.br
.PP
.SS "Bestanden"

.in +1c
.ti -1c
.RI "bestand \fBhmm\&.h\fP"
.br
.ti -1c
.RI "bestand \fBhmm_lib\&.c\fP"
.br
.ti -1c
.RI "bestand \fBhmm_lib\&.h\fP"
.br
.ti -1c
.RI "bestand \fBrun_hmm\&.c\fP"
.br
.ti -1c
.RI "bestand \fBrun_hmm\&.h\fP"
.br
.ti -1c
.RI "bestand \fButil_lib\&.c\fP"
.br
.ti -1c
.RI "bestand \fButil_lib\&.h\fP"
.br
.in -1c
