.TH "HMM" 3 "Wo 17 Jun 2020" "Version 0.1" "FragScanTibo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HMM
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hmm\&.h>\fP
.SS "Public Attributen"

.in +1c
.ti -1c
.RI "double \fBpi\fP [29]"
.br
.ti -1c
.RI "double \fBtr\fP [14]"
.br
.ti -1c
.RI "double \fBtr_I_I\fP [4][4]"
.br
.ti -1c
.RI "double \fBtr_M_I\fP [4][4]"
.br
.in -1c
.SH "Documentatie van data members"
.PP 
.SS "double pi[29]"

.SS "double tr[14]"

.SS "double tr_I_I[4][4]"

.SS "double tr_M_I[4][4]"


.SH "Auteur"
.PP 
Automatisch gegenereerd door Doxygen voor FragScanTibo uit de programmatekst\&.
