.TH "src/hmm_lib.h" 3 "Di 16 Jun 2020" "Version 0.1" "FragScanTibo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hmm_lib.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Functies"

.in +1c
.ti -1c
.RI "void \fBget_rc_dna_indel\fP (char *dna_f, char *dna_f1)"
.br
.in -1c
.SH "Documentatie van functies"
.PP 
.SS "void get_rc_dna_indel (char * dna, char * dna1)"
copies dna to dna1 in reverse\&. and 
.SH "Auteur"
.PP 
Automatisch gegenereerd door Doxygen voor FragScanTibo uit de programmatekst\&.
