.TH "src/hmm_lib.c" 3 "Vr 12 Jun 2020" "Version 0.1" "FragScanTibo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hmm_lib.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include 'hmm\&.h'\fP
.br
\fC#include 'util_lib\&.h'\fP
.br
\fC#include 'hmm_lib\&.h'\fP
.br

.SS "Functies"

.in +1c
.ti -1c
.RI "void \fBviterbi\fP (\fBHMM\fP *hmm_ptr, \fBTRAIN\fP *train_ptr, char *O, FILE *fp_out, FILE *fp_aa, FILE *fp_dna, char *head, int whole_genome, int cg, int format)"
.br
.ti -1c
.RI "int \fBget_prob_from_cg\fP (\fBHMM\fP *hmm_ptr, \fBTRAIN\fP *train_ptr, char *O)"
.br
.ti -1c
.RI "void \fBget_train_from_file\fP (char *filename, \fBHMM\fP *hmm_ptr, char *mfilename, char *mfilename1, char *nfilename, char *sfilename, char *pfilename, char *s1filename, char *p1filename, char *dfilename, \fBTRAIN\fP *train_ptr)"
.br
.ti -1c
.RI "void \fBfree_hmm\fP (\fBHMM\fP *hmm_ptr)"
.br
.ti -1c
.RI "void \fBdump_memory\fP (void *p, int size)"
.br
.in -1c
.SH "Documentatie van functies"
.PP 
.SS "void dump_memory (void * p, int size)"

.SS "void free_hmm (\fBHMM\fP * hmm_ptr)"

.SS "int get_prob_from_cg (\fBHMM\fP * hmm_ptr, \fBTRAIN\fP * train_ptr, char * O)"

.SS "void get_train_from_file (char * filename, \fBHMM\fP * hmm_ptr, char * mfilename, char * mfilename1, char * nfilename, char * sfilename, char * pfilename, char * s1filename, char * p1filename, char * dfilename, \fBTRAIN\fP * train_ptr)"
Reads files\&.
.IP "1." 4
Reads trasition file and store in hmm datastructure 
.PP

.SS "void viterbi (\fBHMM\fP * hmm_ptr, \fBTRAIN\fP * train_ptr, char * O, FILE * fp_out, FILE * fp_aa, FILE * fp_dna, char * head, int whole_genome, int cg, int format)"

.SH "Auteur"
.PP 
Automatisch gegenereerd door Doxygen voor FragScanTibo uit de programmatekst\&.
