.TH "src/hmm_lib.h" 3 "Za 6 Jun 2020" "Version 0.1" "FragScanTibo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hmm_lib.h
.SH SYNOPSIS
.br
.PP
.SS "Functies"

.in +1c
.ti -1c
.RI "void \fBdump_memory\fP (void *p, int size)"
.br
.ti -1c
.RI "void \fBget_rc_dna_indel\fP (char dna_f[300000], char dna_f1[300000])"
.br
.in -1c
.SH "Documentatie van functies"
.PP 
.SS "void dump_memory (void * p, int size)"

.SS "void get_rc_dna_indel (char dna_f[300000], char dna_f1[300000])"

.SH "Auteur"
.PP 
Automatisch gegenereerd door Doxygen voor FragScanTibo uit de programmatekst\&.
