.TH "src/run_hmm.c" 3 "Vr 12 Jun 2020" "Version 0.1" "FragScanTibo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/run_hmm.c
.SH SYNOPSIS
.br
.PP
\fC#include <ctype\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'run_hmm\&.h'\fP
.br
\fC#include 'util_lib\&.h'\fP
.br
\fC#include <pthread\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADD_LEN\fP   1024"
.br
.ti -1c
.RI "#define \fBSTRINGLEN\fP   4096"
.br
.in -1c
.SS "Functies"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.ti -1c
.RI "void * \fBthread_func\fP (void *threadarr)"
.br
.ti -1c
.RI "int \fBappendSeq\fP (char *input, char **seq, int input_max)"
.br
.ti -1c
.RI "void \fBprint_error\fP (const char *error_message,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBprint_file_error\fP (const char *error_message, char *file)"
.br
.in -1c
.SH "Documentatie van macro's"
.PP 
.SS "#define ADD_LEN   1024"

.SS "#define STRINGLEN   4096"

.SH "Documentatie van functies"
.PP 
.SS "int appendSeq (char * input, char ** seq, int input_max)"

.SS "int main (int argc, char ** argv)"
Entry point of program
.IP "1." 4
Initialization of variables and datatypes
.IP "2." 4
Check File acessiblity 
.PP

.SS "void print_error (const char * error_message,  \&.\&.\&.)"
Error function:
.IP "1." 4
Print error message
.IP "2." 4
Call \fBprint_usage()\fP from util_lib
.IP "3." 4
EXIT program 
.PP

.SS "void print_file_error (const char * error_message, char * file)"
Error function:
.IP "1." 4
Print error message
.IP "2." 4
EXIT program 
.PP

.SS "void* thread_func (void * threadarr)"

.SH "Auteur"
.PP 
Automatisch gegenereerd door Doxygen voor FragScanTibo uit de programmatekst\&.
