.TH "src/sprintf_irc.c" 3 "Za 13 Jun 2020" "Version 0.1" "FragScanTibo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sprintf_irc.c
.SH SYNOPSIS
.br
.PP
\fC#include 'sprintf_irc\&.h'\fP
.br

.SS "Functies"

.in +1c
.ti -1c
.RI "int \fBvsprintf_irc\fP (char *str, const char *format, va_list args)"
.br
.ti -1c
.RI "int \fBircsprintf\fP (char *str, const char *format,\&.\&.\&.)"
.br
.in -1c
.SH "Documentatie van functies"
.PP 
.SS "int ircsprintf (char * str, const char * format,  \&.\&.\&.)"

.SS "int vsprintf_irc (char * str, const char * format, va_list args)"

.SH "Auteur"
.PP 
Automatisch gegenereerd door Doxygen voor FragScanTibo uit de programmatekst\&.
