.TH "src/sprintf_irc.h" 3 "Za 13 Jun 2020" "Version 0.1" "FragScanTibo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sprintf_irc.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functies"

.in +1c
.ti -1c
.RI "int \fBircsprintf\fP (char *, const char *,\&.\&.\&.)"
.br
.in -1c
.SH "Documentatie van functies"
.PP 
.SS "int ircsprintf (char *, const char *,  \&.\&.\&.)"

.SH "Auteur"
.PP 
Automatisch gegenereerd door Doxygen voor FragScanTibo uit de programmatekst\&.
